### ISSUE TITLE
Please add a license information

### ISSUE THREAD

**Issue by mrshridhara** [jonathansant/Orleans.Persistence.Redis#6]
Hi, we are trying to use the 0.6.0 version package in one of our products and the corporate OSS governance are not allowing us since there is no license information in the tagged source code archive.

Could you please add a license which you feel is appropriate.

Thanks,
Shridhara Rangaraju

**Comment by claylaut** [comment]
Hi @mrshridhara, I've added the licence file to the library and now I've also updated Microsoft Orleans to the latest version (3.2.0). These changes can be found in version `0.7.0` or later. 

Thanks and good day

**Comment by mrshridhara** [comment]
Thank you @claylaut

**Comment by jaredthirsk** [comment]
@claylaut  Just checking: did you just pick a random license, or did you consciously choose GPL knowing the restrictions it places?  
(I was thinking about trying this library but I am not going to risk any GPL dependencies.  Maybe I should re-think this for server-side software if it is at least not AGPL but I am not going to think about it for now.)

**Comment by jaredthirsk** [comment]
For reference, another Orleans Redis project uses the MIT license:

https://github.com/OrleansContrib/Orleans.Redis/blob/main/LICENSE

Also, StackExchange.Redis also uses the MIT license:

https://github.com/StackExchange/StackExchange.Redis/blob/main/LICENSE
